### ISSUE TITLE
Build side-effects out of build directory cause confusion

### ISSUE THREAD

**Issue by pearu** [omnisci/mapd-core#314]
When using thrift verson 0.2.0, the mapd-core build fails with errors like
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/pearu/git/Quansight/mapd-core/java/thrift/src/gen/com/mapd/thrift/server/MapD.java:[5347,7] method does not override or implement a method from a supertype
<snip couple of screens of similar error lines>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :thrift
```
The error is triggered by make command:
```
cd /home/pearu/git/Quansight/mapd-core/java && MVNPATH=/home/pearu/git/Quansight/mapd-core/java /home/pearu/miniconda3/envs/omnisci-dev-cpu/bin/mvn -q clean install -Dthrift.version="0.12.0" -Dmapd.release.version="4.5.0-SNAPSHOT"
```
When changing this to (replace 0.12.0 with 0.11.0)
```
cd /home/pearu/git/Quansight/mapd-core/java && MVNPATH=/home/pearu/git/Quansight/mapd-core/java /home/pearu/miniconda3/envs/omnisci-dev-cpu/bin/mvn -q clean install -Dthrift.version="0.11.0" -Dmapd.release.version="4.5.0-SNAPSHOT"
```
the command will be successful.

**Comment by pearu** [comment]
Removing `java/thrift/src/` and `java/thrift/target/` directories fixed this issue.

So, apparently mapd-core build has side-effects to directories outside the build directory.

Subsequently, the build succeeds but `mkdir data && bin/initdb data` fails with
```
<snip a bunch of the Connection refused messages>
Thrift: Thu Jan 24 14:32:48 2019 TSocket::open() connect() <Host: localhost Port: 39093>: Connection refused
2019-01-24 14:32:49 ERROR TThreadPoolServer:run:315 - Thrift error occurred during processing of message.
org.apache.thrift.transport.TTransportException
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:425)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:321)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:225)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:310)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
<snip 3x the above>
```

**Comment by pearu** [comment]
Here's an update: despite the error messages, the mapd_server actually works.
